name: Setup Environment and Autograde

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # flake8 src/exercise.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # flake8 src/exercise.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          python3 -m pytest
